baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[build]
  writeStats = true

[build.buildStats]
  enable = true

[[build.buildStats.disableClasses]]
  tags = true

[[build.buildStats.disableIDs]]
  tags = true

[[build.cachebusters]]
  source = "hugo_stats\\.json"
  target = "css"

[[build.cachebusters]]
  source = "(postcss|tailwind)\\.config\\.js"
  target = "css"

[[build.cachebusters]]
  source = "layouts/.*\\.html"
  target = "css"

[[build.cachebusters]]
  source = "content/.*\\.md"
  target = "css"
